'use strict';

/**
 * Stable machine-readable diagnostics for the composition domain.
 *
 * Codes are API. Human messages may improve without a schema bump; a code may
 * not be reused for another meaning. Phase 1a reserves the resolver/update
 * codes now so the CLI and the studio can share one vocabulary later.
 */
const DIAGNOSTIC_CODES = Object.freeze({
    DOCUMENT_INVALID: 'NC_COMPOSE_DOCUMENT_INVALID',
    SCHEMA_VERSION_UNSUPPORTED: 'NC_COMPOSE_SCHEMA_VERSION_UNSUPPORTED',
    COURSE_ID_INVALID: 'NC_COMPOSE_COURSE_ID_INVALID',
    ENTITY_ID_INVALID: 'NC_COMPOSE_ENTITY_ID_INVALID',
    ENTITY_OWNER_MISMATCH: 'NC_COMPOSE_ENTITY_OWNER_MISMATCH',
    ENTITY_KIND_MISMATCH: 'NC_COMPOSE_ENTITY_KIND_MISMATCH',
    ENTITY_DUPLICATE: 'NC_COMPOSE_ENTITY_DUPLICATE',
    VERSION_INVALID: 'NC_COMPOSE_VERSION_INVALID',
    PATH_INVALID: 'NC_COMPOSE_PATH_INVALID',
    EXPORT_TARGET_INVALID: 'NC_COMPOSE_EXPORT_TARGET_INVALID',
    RECIPE_INVALID: 'NC_COMPOSE_RECIPE_INVALID',
    RECIPE_NOT_FOUND: 'NC_COMPOSE_RECIPE_NOT_FOUND',
    GROUP_DUPLICATE: 'NC_COMPOSE_GROUP_DUPLICATE',
    OCCURRENCE_DUPLICATE: 'NC_COMPOSE_OCCURRENCE_DUPLICATE',
    ITEM_INVALID: 'NC_COMPOSE_ITEM_INVALID',
    CONTENT_MODE_INVALID: 'NC_COMPOSE_CONTENT_MODE_INVALID',
    UPDATE_POLICY_INVALID: 'NC_COMPOSE_UPDATE_POLICY_INVALID',
    VARIANT_BASELINE_MISSING: 'NC_COMPOSE_VARIANT_BASELINE_MISSING',
    HASH_INVALID: 'NC_COMPOSE_HASH_INVALID',
    LOCK_REFERENCE_INVALID: 'NC_COMPOSE_LOCK_REFERENCE_INVALID',
    REFERENCE_NOT_FOUND: 'NC_COMPOSE_REFERENCE_NOT_FOUND',
    EXPORT_NOT_PUBLIC: 'NC_COMPOSE_EXPORT_NOT_PUBLIC',
    REFERENCE_CYCLE: 'NC_COMPOSE_REFERENCE_CYCLE',
    DUPLICATE_PATH: 'NC_COMPOSE_DUPLICATE_PATH',
    VERSION_CONFLICT: 'NC_COMPOSE_VERSION_CONFLICT',
    SNAPSHOT_MISSING: 'NC_COMPOSE_SNAPSHOT_MISSING',
    SOURCE_DRIFT: 'NC_COMPOSE_SOURCE_DRIFT',
    PLAN_STALE: 'NC_COMPOSE_PLAN_STALE',
    GENERATED_DRIFT: 'NC_COMPOSE_GENERATED_DRIFT',
    ASSET_MISSING: 'NC_COMPOSE_ASSET_MISSING',
    ASSET_PATH_UNRESOLVED: 'NC_COMPOSE_ASSET_PATH_UNRESOLVED',
    PREREQUISITE_MISSING: 'NC_COMPOSE_PREREQUISITE_MISSING',
    OUTCOME_EVIDENCE_MISSING: 'NC_COMPOSE_OUTCOME_EVIDENCE_MISSING',
    DURATION_OVER_BUDGET: 'NC_COMPOSE_DURATION_OVER_BUDGET',
    CASE_MATERIAL_INVALID: 'NC_COMPOSE_CASE_MATERIAL_INVALID',
    CASE_ANSWER_MISSING: 'NC_COMPOSE_CASE_ANSWER_MISSING',
    GENERATOR_OUTPUT_INVALID: 'NC_COMPOSE_GENERATOR_OUTPUT_INVALID',
    DELIVERY_PROFILE_INVALID: 'NC_COMPOSE_DELIVERY_PROFILE_INVALID',
    DELIVERY_AUDIENCE_LEAK: 'NC_COMPOSE_DELIVERY_AUDIENCE_LEAK',
});

function diagnostic(code, message, path = '', severity = 'error', details) {
    const out = { code, severity, message, path };
    if (details !== undefined) out.details = details;
    return out;
}

module.exports = { DIAGNOSTIC_CODES, diagnostic };
